# Generated by Django 3.1 on 2020-09-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='autor',
            new_name='author',
        ),
    ]
